import Image from 'next/image'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

import './globals.css'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={raleway.className}>
        <header>
          <Image alt='churras bg' width='636' src='/bg.png' height='203' className='max-h-[203px] object-fill backdrop-blur-sm'/>
          <h1>Agenda de Churras</h1>
        </header>
        {children}
      </body>
    </html>
  )
}
